### PR TITLE
Upgrade new DellEMC platforms to bullseye kernel

### PR DESCRIPTION
**Pull request by aravindmani-1**
#### Why I did it
Upgrade DellEMC platforms to bullseye.
#### How I did it
Modified Dell platform files
#### How to verify it
Execute platform related commands and verify the behavior.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by aravindmani-1** [comment]
@saiarcot895 Can you please review this PR?

**Comment by saiarcot895** [comment]
Reviewed. On a side note, are the `sonic_platform/ipmihelper.py` files for each platform auto-generated files? If so, is it safe to remove them from the repo, and let the build generate them?

**Comment by aravindmani-1** [comment]
> Reviewed. On a side note, are the `sonic_platform/ipmihelper.py` files for each platform auto-generated files? If so, is it safe to remove them from the repo, and let the build generate them?

ipmihelper will be present only under common directory. https://github.com/Azure/sonic-buildimage/blob/f6ec932b3cb1a78f79bf0af9c72c1f9ae060332c/platform/broadcom/sonic-platform-modules-dell/common/ipmihelper.py. We copy this file to each platform while building the debian. https://github.com/Azure/sonic-buildimage/blob/f6ec932b3cb1a78f79bf0af9c72c1f9ae060332c/platform/broadcom/sonic-platform-modules-dell/debian/rules.

**Comment by saiarcot895** [comment]
Some platforms have the file checked in as well, like [z5248f](https://github.com/Azure/sonic-buildimage/blob/f6ec932b3cb1a78f79bf0af9c72c1f9ae060332c/platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/ipmihelper.py) and [n3248pxe](https://github.com/Azure/sonic-buildimage/blob/fcff3f3d09a7ea87b22f9a3212243e27ea03c590/platform/broadcom/sonic-platform-modules-dell/n3248pxe/sonic_platform/ipmihelper.py). Can those be removed then, since they're going to get overwritten anyways?

**Comment by aravindmani-1** [comment]
> Some platforms have the file checked in as well, like [z5248f](https://github.com/Azure/sonic-buildimage/blob/f6ec932b3cb1a78f79bf0af9c72c1f9ae060332c/platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/ipmihelper.py) and [n3248pxe](https://github.com/Azure/sonic-buildimage/blob/fcff3f3d09a7ea87b22f9a3212243e27ea03c590/platform/broadcom/sonic-platform-modules-dell/n3248pxe/sonic_platform/ipmihelper.py). Can those be removed then, since they're going to get overwritten anyways?
> 
> One advantage of this is that if the build of the Dell platform modules fails for whatever reason, or I interrupt the build while they're building, git doesn't say that those files have been removed because of that build failure/interruption.

Sure. These are recently added platforms, i'll remove the files for these platforms and add ipmihelper in platform debian rules.

**Pull request merged**
