### PR TITLE
Update Barefoot  platform module for Bullseye and 5.10 kernel

### PR DESCRIPTION
**Pull request by KostiantynYarovyiBf**
#### Why I did it
Update Barefoot platform support for Bullseye and 5.10 kernel
#### How I did it

1.  modify Barefoot platform driver for linux 5.10
2.  add python3-venv  for bullseye

#### How to verify it
build image  with kernel 5.10 and verify on Barefoot board
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by saiarcot895** [comment]
Also, is the submodule update for Arista still needed? I recall seeing some comments on a PR saying that the necessary changes were already done.

**Comment by saiarcot895** [comment]
Manually merged in everything except for the submodule update; recent commits suggest that it's not needed, and a local build for Arista on Broadcom succeeded without the submodule change.

**Comment by KostiantynYarovyiBf** [comment]
> Manually merged in everything except for the submodule update; recent commits suggest that it's not needed, and a local build for Arista on Broadcom succeeded without the submodule change.

I update submodule on latest master (hash d82bb20) according to discussion on this PR:
https://github.com/aristanetworks/sonic/pull/32
It necessary for build on Barefoot.

How to verified:

1. make init 
2. make configure PLATFORM=barefoot
3. make all
4. make target/sonic-aboot-barefoot.swi
5. deploy sonic on test bed and check syncd container after 3 mins (docker ps -a) 
6. or check show interface status and so on. 
Without this fix interfaces will be absent, syncd crashed.

Also the latest commits are necessary for successful build Sonic Barefoot.

P.s. Sorry for the late reply

**Comment by KostiantynYarovyiBf** [comment]
> What's the purpose of `python3-venv`? Will Arista's Python scripts need to be run in a virtualenv?

I'll double-check this without `python3-venv`

**Pull request closed without merging**
